### ISSUE TITLE
RPC function called "Connect" conflicts with auto-generated "connect"

### ISSUE THREAD

**Issue by gtaubman** [hyperium/tonic#1253] opened 2023-01-29 01:39 UTC
Hello!

I have an RPC service defined as follows:

```
message Request {}
message Response {}

service MyService {
  rpc Connect(stream Request) returns (stream Response);
}
```

When I build an RPC client using tonic, I get the following error that there are duplicate definitions of `connect()`, because tonic (or maybe it's prost I'm not sure?) auto-generates a method called `connect()` as well:

```
error[E0592]: duplicate definitions with name `connect`
    --> server_definition.proto.rs:481
    |
481 | /         pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
482 | |         where
483 | |             D: std::convert::TryInto<tonic::transport::Endpoint>,
484 | |             D::Error: Into<StdError>,
    | |_____________________________________^ duplicate definitions for `connect`
...
541 | /         pub async fn connect(
542 | |             &mut self,
543 | |             request: impl tonic::IntoStreamingRequest<Message = super::Request>,
544 | |         ) -> Result<
545 | |             tonic::Response<tonic::codec::Streaming<super::Response>>,
546 | |             tonic::Status,
547 | |         > {
    | |_________- other definition for `connect`
```

I'm unable to change the name of the RPC in the service definition.  Does anyone have any suggestions for how I can work around this problem?

I'm using the following dependency versions:
```
prost = "0.11.6"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.8.3"
```

**Comment by b-camacho** [comment] 2023-02-07 22:58
Duplicate of https://github.com/hyperium/tonic/issues/747
I think this is a good indication people are still running into this, so we may need a more general fix?

**Comment by b-camacho** [comment] 2023-02-07 23:14
I have a draft PR here https://github.com/hyperium/tonic/pull/1261, still need to add some unit tests and resolve merge conflicts

**Comment by LucioFranco** [comment] 2023-02-08 14:08
Does this not fix your use case? https://github.com/hyperium/tonic/issues/747#issuecomment-1048157380

**Comment by b-camacho** [comment] 2023-02-09 06:50
While disabling the transport feature fixes the name collisions, I find the transport feature very useful, so I don't want to disable it - the workaround seems sub-optimal in that sense

**Comment by LucioFranco** [comment] 2023-02-13 14:56
While I think it is sub-optimal, I also believe renaming connect isn't optimal either. The workaround without using connect isn't that much code either since there is an equivalent connect method on `Endpoint`. `connect` imho is more of a nice thing to have than a required part of the api.

**Closed by LucioFranco** 2023-02-13 14:56 UTC

**Comment by b-camacho** [comment] 2024-01-18 01:30
This confused me a bit at first, but disabling the tonic-build `transport` feature works indeed! Here's a [small example](https://github.com/b-camacho/tonic-name-collision/blob/master/Cargo.toml#L14)
