### ISSUE TITLE
FATA[0000] getting the runtime version: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Ruilkyu** [hyperium/tonic#576] opened 2021-03-06 05:24 UTC
crictl --runtime-endpoint unix:///var/run/dragonforce.sock version
FATA[0000] getting the runtime version: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

**Comment by davidpdrsn** [comment] 2021-03-06 12:40
Sorry but, what..?

**Comment by Ruilkyu** [comment] 2021-03-06 12:42
Go grpc can't send data to the UNIX socket server of tone

**Comment by davidpdrsn** [comment] 2021-03-06 12:51
Are you able to provide a minimal reproducible example? I don't know go.

**Comment by Ruilkyu** [comment] 2021-03-06 12:53
similar to #243

**Comment by Ruilkyu** [comment] 2021-03-06 14:51
I have a big project on my side, which relies on tonic.I hope it can be solved quickly.It's very helpful for promotion tonic.

**Comment by davidpdrsn** [comment] 2021-03-06 15:15
Without a way of reproducing the error is hard to fix.

**Comment by davidpdrsn** [comment] 2021-05-01 17:04
I'm going to close this. Feel free to re-open if you're able to provide more details.

**Closed by davidpdrsn** 2021-05-01 17:04 UTC
Labels: S-waiting-on-author

**Comment by Forsworns** [comment] 2022-11-18 04:58
For anyone who encounter the same problem:

@davidpdrsn The problem is due to the `:authority` field in the request from unix domain socket (UDS). And I believe that discussions on [https://github.com/hyperium/h2/pull/487#issuecomment-1080658944] show the origin. 

It's not the problem with tonic, but the related PR in `hyperium/h2` has been pended for so long a time that we still encounter the same problem in 2022... 

To reproduce:

On the golang side
```go
conn, err := grpc.Dial("/var/example.sock",
  grpc.WithInsecure(),
  grpc.WithContextDialer(func(ctx context.Context, addr string) (net.Conn, error) {
	  return (&net.Dialer{}).DialContext(ctx, "unix", addr)
  }),
) 
```

On the rust side, listen to the above UDS via tonic, and you can get this error.

However, the following grpc-go client works well
```go
conn, err := grpc.Dial("unix:///var/example.sock",
	grpc.WithInsecure(),
) 
```

**Comment by Forsworns** [comment] 2022-11-18 05:48
Just met the same problem these days. 

In fact, it's due to a wrong usage of grpc. And this is not the problem of tonic. 

There is a related discussion in hyperium/h2#487

The problem can be reproduced by following grpc-go client

```go
conn, err := grpc.Dial("/var/sock.sock",
  grpc.WithInsecure(),
  grpc.WithContextDialer(func(ctx context.Context, addr string) (net.Conn, error) {
    return (&net.Dialer{}).DialContext(ctx, "unix", addr)
  }),
) 
```

Because the `grpc.withAuthority` is not used.
