### ISSUE TITLE
Unable to detect client disconnection on server side streaming

### ISSUE THREAD

**Issue by stefandanaita** [hyperium/tonic#377] opened 2020-06-21 15:36 UTC
Hi guys! Firstly, I want to thank you for this amazing library! The docs are good as well, but I've struggled to find a way to detect (on the server side) when the client connection drops.

I've spent a lot of time trying to figure out this comment that @LucioFranco left about this [here](https://github.com/hyperium/tonic/issues/196#issuecomment-567137432) #196, but I couldn't get it working. If someone that did this already could provide an example, that would be amazing!

I'm aware that gRPC streaming is not very popular yet, but I expect others to bump into this issue down the line, so it would be good to stick this into the docs somewhere. Happy to raise a PR for that if I can get some help getting it working myself 😢 

Thank you!

**Comment by LucioFranco** [comment] 2020-06-22 14:30
@stefandanaita what were the issues you ran into with that solution?

**Comment by stefandanaita** [comment] 2020-06-22 15:24
Hi @LucioFranco! It might be due to my still growing 🦀 knowledge, but here's what I struggled with

Firstly, when trying to write my own Stream implementation, like you suggested below, I assumed you were referring to `poll_next` instead of `poll_accept`, however I couldn't figure out how to forward the call to the inner Receiver 🤔 

```rust
pub struct MyStream(mpsc::Receiver<Result<Msg, Status>>);

// In here you just need to forward the `poll_accept` call
// to the inner `Reciever`.
impl Stream for MyStream {
    type Item = mpsc::Receiver<Result<Msg, Status>>; // I guess this is alright

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        unimplemented!() // Not sure what this body should be
    }
}

impl Drop for MyStream {
    fn drop(&mut self) {
        println!("Stream dropped! Client disconnected!");
    }
}
```

Secondly, I'm not sure how to hook this custom stream to the gRPC Service implementation. The `oneshot` channel part should be easy once I figure out how to get that `drop` function called.

Would it be possible to extend the [server side streaming example](https://github.com/hyperium/tonic/blob/master/examples/src/routeguide/server.rs#L40) and include this scenario? 😄 

Thank you!!

**Comment by LucioFranco** [comment] 2020-07-01 18:51
That is correct, for the receiver you can just forward the poll_next call to the `Stream::poll_next` on the receivers stream implementation. The drop method will be called when the stream ends.

**Comment by stefandanaita** [comment] 2020-07-03 14:02
Everything seems fine apart from the poll_next forwarding. I've tried this

```rust
impl Stream for MyStream {
    type Item = Result<VideoResponse, Status>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Stream::poll_next(self, cx)
    }
}
```

However, this gets me into an [recursive infinite loop like the one here](https://www.reddit.com/r/rust/comments/3uvfgx/how_to_call_default_trait_method/?sort=top). Do you know how I could go around that? I couldn't find a way to forward a call to the underlying trait in Rust 🤔

**Comment by LucioFranco** [comment] 2020-07-06 14:25
@stefandanaita make sure that you are polling the inner stream not your struct.

```rust
struct MyStream {
  rx: mpsc::Receiver<...>,
}

impl Stream for MyStream {
    type Item = Result<VideoResponse, Status>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Pin::new(&mut self.rx).poll_next(cx)
    }
}
```

**Comment by LucioFranco** [comment] 2020-07-06 14:26
You can also use this to get around the need to pin https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html#method.poll_next_unpin

**Comment by siebeclaes** [comment] 2020-07-06 17:46
Hi Guys,

for what it's worth, I also ran into this requirement last week and was able to solve it in a similar way. The following code is how I got it working in my application (adapted a bit to use a oneshot channel instead of mpsc with custom message):

```rust
pub struct DropReceiver<T> {
    chan: oneshot::Sender<usize>,
    inner: mpsc::Receiver<T>,
}

impl<T> tokio::stream::Stream for DropReceiver<T> {
    type Item = T;

    fn poll_next(mut self: std::pin::Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<T>> {
        self.inner.poll_recv(cx)
    }
}

impl<T> Deref for DropReceiver<T> {
    type Target = mpsc::Receiver<T>;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl<T> Drop for DropReceiver<T> {
    fn drop(&mut self) {
        debug!("Receiver has been dropped");
        self.chan.send(1).await;
    }
}

// In the Service function:
let (tx, rx) = mpsc::channel(4); // Channel for the server-side streaming
let (oneshot_tx, oneshot_rx) = oneshot::channel();

let rx = DropReceiver {
    chan: oneshot_tx;
    inner: rx,
};

// Send the oneshot_rx somewhere else to detect the client dropping
Ok(Response::new(rx))
```

I'm not sure whether the Deref is actually necessary though. Still very new to Rust/Tonic.
Hope this helps with your problem @stefandanaita

**Comment by siebeclaes** [comment] 2020-07-06 17:58
I just now noticed that I'm forwarding the `poll_next` call to inner `poll_recv` instead of inner `poll_next`. I did this because without pinning the compiler throws the following error:

```
error[E0599]: no method named `poll_next` found for struct `tokio::sync::mpsc::bounded::Receiver<T>` in the current scope
  --> src/central.rs:42:20
   |
42 |         self.inner.poll_next(cx)
   |                    ^^^^^^^^^ help: there is an associated function with a similar name: `poll_recv`
```
So I just replaced the `inner.poll_next()` with `inner.poll_recv()` and it worked. But evidently this is not the proper way to do it. Pinning as @LucioFranco mentioned works and I can forward to `inner.poll_recv()`. The code for the `impl Stream` then becomes:
```rust
impl<T> tokio::stream::Stream for DropReceiver<T> {
    type Item = T;

    fn poll_next(mut self: std::pin::Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Pin::new(&mut self.inner).poll_next(cx)
    }
}
```
and I can confirm this works. But no idea what the difference is between this (with pinning) and the other one without pinning but forwarding to `poll_recv()`

**Comment by LucioFranco** [comment] 2020-07-06 18:00
`poll_recv` is likely a private fn we have within tokio that doesn't actually require pinning. Glad that worked!

**Comment by stefandanaita** [comment] 2020-07-06 18:13
Thanks @siebeclaes! I've managed to get it working with Lucio's suggestions 15 minutes ago! I'll steal the oneshot stuff from you though!

I still think it's worth documenting this stuff, @LucioFranco would you accept a PR? If positive, I'll find the time to do it 😄 

Thanks a lot to both of you!

**Comment by LucioFranco** [comment] 2020-07-06 18:18
@stefandanaita totally! I would love any help in what you think would make this a bit easier to discover :)

**Comment by LucioFranco** [comment] 2020-07-27 18:59
Going to close this, feel free to re-open if you have anymore questions.

**Closed by LucioFranco** 2020-07-27 18:59 UTC

**Comment by s00500** [comment] 2020-10-08 11:14
Hi everyone, chipping on this as I need to get this to work, as a few more of you I am just getting started with rust/tokio/tonic...

My questions to @siebeclaes code: first you are using the oneshot in the Drop implementation as a future.. what oneshot are you using ? futures implementation ? or tokios ? also calling await in a non async block is usually forbidden, so it does not compile for me... If I remove it and try to use tokios oneshot it will of course drop the sender on send(), and this does not work as well since move of self inside a &mut self fuction is also forbidden...

As I can read from you post you where probably using the mpsc channel instead in reality...

I can clearly see that detecting the drop of the reciever in the log works, but I do not know how to successfully use the oneshot to fire the info back to the other async task... Also: what is the advantage of using a oneshot here instead of another channel ?

Can you explain a little more what is going on there and how you made it work finally ? I really would like to understand this construct a little more...

**Comment by s00500** [comment] 2020-10-08 12:49
As for now I have solved the issue for myself by using tokio::sync::mpsc::unbounded_channel, as this allows me to do the send synchronously, and also does not consume itself.

I still would like to know your opinions and solutions to get some more ideas on how to deal with async / sync code mixtures like this, thanks

**Comment by aegonz** [comment] 2021-02-09 18:10
I tried to implement @siebeclaes code but it is throwing this error

> error: cannot move out of `self.chan` which is behind a mutable reference
> label: move occurs because `self.chan` has type `tokio::sync::oneshot::Sender<usize>`, which does not implement the `Copy` trait

Here is the code

```
use std::task::{Context, Poll};
use std::pin::Pin;

use tokio::sync::{mpsc, oneshot};
use futures::Stream;

pub struct DropReceiver<T> {
    chan: oneshot::Sender<usize>,
    inner: mpsc::Receiver<T>,
}

impl<T> Stream for DropReceiver<T> {
    type Item = T;

    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Option<Self::Item>> {
        Pin::new(&mut self.inner).poll_recv(cx)
    }
}

impl<T> Drop for DropReceiver<T> {
    fn drop(&mut self) {
        println!("Receiver has been dropped");
        if let Err(_) = self.chan.send(1) {
            println!("the receiver dropped");
        }
    }
}
```
