### ISSUE TITLE
Support retrieve name of NamedService by instance

### ISSUE THREAD

**Issue by tisonkun** [hyperium/tonic#929] opened 2022-02-26 04:13 UTC
### Crates

`tonic`

### Motivation

When I'm trying to [retrieve name of health service](https://github.com/engula/engula/blob/2ba773d2a32781f0b04a863873636a04cd9722de/src/engula/src/server.rs#L87-L89), it's impossible since the exact type consist an inner struct. Although I can still copy the name string literally and fallback to `set_service_status` interface, it would be reasonable to retrieve the name of `NamedService` by instance.

### Proposal

I'll submit a patch and it should simply add a getter.

### Alternatives

N/A

**Comment by LucioFranco** [comment] 2022-03-01 21:12
Could you explain more your use case? I would imagine it still possible to use the const field from the trait without a method.

**Comment by tisonkun** [comment] 2022-03-02 01:02
> I would imagine it still possible

That would be nice. Could you share a code snippet how to?

So far, base on #930 I can write as below ([src](https://github.com/tisonkun/playground-rs/blob/01266f2c146a95f983c2104d7ab883a10c430e49/healthcheck/src/main.rs#L24-L25)):

```rust
let (mut health_reporter, health_server) = tonic_health::server::health_reporter();
let health_server_name = health_server.name();
```

But I may not a Rust expert and don't know how to access the const field since `HealthService` is not exported.

**Comment by LucioFranco** [comment] 2022-03-02 18:57
Ah okay I see, I think the better route would be to just make `HealthService` public instead of adding a method to the trait. What do you think?

**Comment by tisonkun** [comment] 2022-03-03 14:23
@LucioFranco that's OK for my use case. I'm curious why add a method is a bad idea.

**Comment by LucioFranco** [comment] 2022-03-03 16:19
@tisonkun its a duplicate of what you can already do and I'd like to avoid extra stuff we don't need :)

**Comment by tisonkun** [comment] 2022-03-04 06:32
@LucioFranco make sense. Let me adjust the PR in this way.

**Closed** 2022-03-18 21:37 UTC

**Comment by jctaoo** [comment] 2023-08-17 17:33
I My usecase is to bind tonic service to axum router described at https://github.com/hyperium/tonic/discussions/1111 , code like:

```rust
    let grpc_route = axum::Router::new()
        .route(
            "/enhance_ws.RealtimeHandler/*rpc",
            axum::routing::any_service(RealtimeHandlerServer::new(grpc_service)),
        )
        .route(
            "/enhance_ws.webhook.WebhookScriptManage/*rpc",
            // format!(WebhookScriptManageServer::),
            axum::routing::any_service(WebhookScriptManageServer::new(web_hook_service)),
        )
        .layer(from_fn(|req, next| grpc_auth_layer(req, next, token)))
        .with_state(app_state.clone());
```

if it's possible to retrieve name of service, I can do something like:

```rrust
.route(
            format!("{}/*rpc", WebhookScriptManageServer::name),
            axum::routing::any_service(WebhookScriptManageServer::new(web_hook_service)),
)
```

and it's also useful in binding dynamic service to route.
