### ISSUE TITLE
TLS request.remote_addr() returns null

### ISSUE THREAD

**Issue by yamashi** [hyperium/tonic#483] opened 2020-10-24 17:28 UTC
### Version

tonic v0.3.1

### Platform

Windows 64 bits

### Crates

tonic v0.3.1

### Description

When using TLS the Request<T> passed to the implementation returns a None object.

Expected behavior: return the remote address.

**Comment by Nako11** [comment] 2020-11-04 15:10
I can confirm that the error also occurs on Mac OS and Linux with tonic v0.3.1.

This is most likeley due to the fact, that the ConnectionInfo is created at a moment ("transport/server/mod.rs" , line 590) when the state of the TlsStream is not updated and still in the initial Handshaking case. The way the remote_addr function for the TlsStream works at the moment is, that if its state is in the Handshaking case it will return None:
`rust
impl<T: Connected> Connected for TlsStream<T> {
fn remote_addr(&self) -> Option<SocketAddr> {
     if let Some((inner, _)) = self.get_ref() {
           inner.remote_addr()
        } else {
            None
        }
     }
`
I see no other code where the connection info in the extensions is updated.

A quick and dirty workaround is to save the remote_addr before the handshake ist accepted and pass it to the creation of the TlsStream (**Disclaimer** I am no expert and don't know if this has any negative impact on security!):

`rust
#[cfg_attr(not(feature = "tls"), allow(unused_variables))]    
pub(crate) fn tcp_incoming<IO, IE>(    
    incoming: impl Stream<Item = Result<IO, IE>>,    
    server: Server,    
) -> impl Stream<Item = Result<ServerIo, crate::Error>>    
where    
    IO: AsyncRead + AsyncWrite + Connected + Unpin + Send + 'static,    
    IE: Into<crate::Error>,    
{    
    async_stream::try_stream! {    
        futures_util::pin_mut!(incoming);    
    
        while let Some(stream) = incoming.try_next().await? {    
            #[cfg(feature = "tls")]    
            {    
                if let Some(tls) = &server.tls {    
                    let remote_addr = stream.remote_addr();    // <----------- here
                    let io = tls.accept(stream, remote_addr);    
                    yield ServerIo::new(io);    
                    continue;    
                }    
            }    
    
            yield ServerIo::new(stream);    
        }    
    }    
}    
`

**Comment by Nako11** [comment] 2020-11-05 10:24
The peer_certs are also in the same situation. You can check it in the "tls-client-auth-server" example. The unary_echo method will never print any peer certs.

**Comment by Nako11** [comment] 2020-11-05 17:32
I had a little bit more time to look at this. remote_addr and peer_certs can both be fixed if we await the Accept-Future from rustls before we create the connection-info. The accept method could be made async:
```
    pub(crate) async fn accept<IO>(&self, io: IO) -> Option<TlsStream<IO>>    
    where                               
        IO: AsyncRead + AsyncWrite + Connected + Unpin + Send + 'static,    
    {    
        let acceptor = RustlsAcceptor::from(self.inner.clone());    
        let stream = acceptor.accept(io).await.ok()?;    
                   
        Some(TlsStream::new(stream))    
    }                   
```
and then awaited while incomming: 
```
pub(crate) fn tcp_incoming<IO, IE>(    
    incoming: impl Stream<Item = Result<IO, IE>>,    
    server: Server,    
) -> impl Stream<Item = Result<ServerIo, crate::Error>>    
where    
    IO: AsyncRead + AsyncWrite + Connected + Unpin + Send + 'static,    
    IE: Into<crate::Error>,    
{    
    async_stream::try_stream! {    
        futures_util::pin_mut!(incoming);    
    
        while let Some(stream) = incoming.try_next().await? {    
            #[cfg(feature = "tls")]    
            {    
                if let Some(tls) = &server.tls {    
                    if let Some(io) = tls.accept(stream).await {    
                        yield ServerIo::new(io);    
                    }    
                    continue;    
                }    
            }    
    
            yield ServerIo::new(stream);    
        }    
    }    
}    
```
We then would not need the Handshaking state for the TlsStream. 
Is there a reason why the evaluation of the Accept-Future is delayed? When the Tls-Connection can not be validated we dont have to bother to continue, right?

**Comment by thienpow** [comment] 2020-11-15 13:50
https://github.com/hyperium/hyper/issues/2321

**Comment by LucioFranco** [comment] 2020-11-18 17:31
duplicate of https://github.com/hyperium/tonic/issues/325

**Comment by LucioFranco** [comment] 2020-11-18 17:31
I will try and get an example out of how to work around this but @thienpow is correct, a lot of this work will depend on what we figure out in hyper. Closing this since its a duplicate.

**Closed by LucioFranco** 2020-11-18 17:31 UTC
