### ISSUE TITLE
tonic-build generate documentation that makes `cargo test --doc` fail for `google/protobuf/timestamp.proto`

### ISSUE THREAD

**Issue by xoac** [hyperium/tonic#967] opened 2022-04-07 12:09 UTC
### Version

```
├── tonic v0.7.1
└── tonic-reflection v0.4.0
    └── tonic v0.7.1 (*)
    └── tonic-build v0.7.0
└── tonic-build v0.7.0 (*)
```

### Platform

```
5.17.0-1-MANJARO #1 SMP PREEMPT Mon Mar 7 08:29:54 UTC 2022 x86_64 GNU/Linux
```

### Description

I used `.compile_well_known_types(true)`  what is related to #964 then I ran `cargo test` and I got errors. That errors are from documentation part of file `(...)/out/google.protobuf.rs`

<details>
<summary>
here is my build stage
</summary>

```rust
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let includes = [proto_root];
    tonic_build::configure()
        .include_file("mod.rs")
        .build_server(true)
        .compile_well_known_types(true)
        .file_descriptor_set_path(out_dir.join("proto_descriptor.bin"))
        .compile(&protos, &includes)
        .expect("compilable proto buf definition");

```
</details>

<details>
<summary>
Here is a head of generated `(...)/out/google.protobuf.rs` file:
</summary>

```
/// A Timestamp represents a point in time independent of any time zone or local
/// calendar, encoded as a count of seconds and fractions of seconds at
/// nanosecond resolution. The count is relative to an epoch at UTC midnight on
/// January 1, 1970, in the proleptic Gregorian calendar which extends the
/// Gregorian calendar backwards to year one.
///
/// All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
/// second table is needed for interpretation, using a [24-hour linear
/// smear](<https://developers.google.com/time/smear>).
///
/// The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
/// restricting to that range, we ensure that we can convert to and from [RFC
/// 3339](<https://www.ietf.org/rfc/rfc3339.txt>) date strings.
///
/// # Examples
///
/// Example 1: Compute Timestamp from POSIX `time()`.
///
///     Timestamp timestamp;
///     timestamp.set_seconds(time(NULL));
///     timestamp.set_nanos(0);
///
```
</details>

And first error:
```
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `timestamp`
 --> /home/sr/projects/github.com/XDeFi-tech/sol-indexer-rs/target/debug/build/sol-xdefi-api-0e9f1572539c1ced/out/google.protobuf.rs:20:11
  |
3 | Timestamp timestamp;
  |           ^^^^^^^^^ expected one of 8 possible tokens

error: aborting due to previous error
```
This error is because doc test treat example part as rust code. All other erros have the same reason

Any suggestion for workaround or change for quick fix?

**Comment by LucioFranco** [comment] 2022-04-07 17:32
Oh I wonder if this is new doc they added. Do you have a reproduction of this I can  run locally?

**Comment by xoac** [comment] 2022-04-07 21:08
Yes. I pushed  reproduction to this repo: https://github.com/xoac/reproduction-tonic-967-issue
I also add CI where you can see errors: https://github.com/xoac/reproduction-tonic-967-issue/runs/5875857022

Hope it helps!

**Comment by LucioFranco** [comment] 2022-04-08 15:11
This is really weird I am not sure why its picking that code up in the doc tests. I have a play ground here for a repro https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5bae9f522bcb6941ccb356289dfeb33f

**Comment by LucioFranco** [comment] 2022-04-08 15:12
Going to close this issue infavor of https://github.com/tokio-rs/prost/issues/621 since this is actually a prost issue.

**Closed by LucioFranco** 2022-04-08 15:12 UTC
