### ISSUE TITLE
Cannot build tonic-reflection 0.4.0 with tonic 0.7.2 + compression

### ISSUE THREAD

**Issue by ppodolsky** [hyperium/tonic#1011] opened 2022-05-31 19:25 UTC
Hi!

```
error[E0308]: mismatched types
   --> ./bazel-out/k8-opt/bin/external/crate_index__tonic-reflection-0.4.0/tonic-reflection_build_script.out_dir/grpc.reflection.v1alpha.rs:337:33
    |
337 | ...                   accept_compression_encodings,
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `EnabledCompressionEncodings`, found `()`

error[E0308]: mismatched types
   --> ./bazel-out/k8-opt/bin/external/crate_index__tonic-reflection-0.4.0/tonic-reflection_build_script.out_dir/grpc.reflection.v1alpha.rs:338:33
    |
338 | ...                   send_compression_encodings,
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `EnabledCompressionEncodings`, found `()`

error: aborting due to 2 previous errors
```

**Comment by g0hl1n** [comment] 2022-06-07 18:11
Hi,
thanks for reporting an issue.

The error you provided suggests you messed up some types in rust. But to be sure, can you please share a minimal version of your proto and rust source so somebody can try to reproduce the problem?

Thanks!

**Comment by ppodolsky** [comment] 2022-06-07 18:40
Not sure what do you mean by me messing some types. It is reproducable merely by

`Cargo.toml`
```toml
[package]
edition = "2021"
name = "test"
version = "0.0.0"

[[bin]]
name = "test"
path = "test.rs"

[dependencies]
tonic = { version = "0.7.2", features = ["compression"] }
tonic-reflection = "0.4.0"
```

and
`test.ts`
```rust
fn main() {}
```

then
```bash
Pashas-MacBook-Pro:error pasha$ cargo build
    Updating crates.io index
  Downloaded async-trait v0.1.56
  Downloaded tower-http v0.3.4
  Downloaded tokio-macros v1.8.0
  Downloaded tokio-util v0.7.3
  Downloaded tokio-stream v0.1.9
  Downloaded syn v1.0.96
  Downloaded http v0.2.8
  Downloaded tokio v1.19.2
  Downloaded 8 crates (1.2 MB) in 1.01s
   Compiling proc-macro2 v1.0.39
   Compiling unicode-ident v1.0.0
   Compiling syn v1.0.96
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.126
   Compiling log v0.4.17
   Compiling autocfg v1.1.0
   Compiling bytes v1.1.0
   Compiling pin-project-lite v0.2.9
   Compiling lazy_static v1.4.0
   Compiling futures-core v0.3.21
   Compiling either v1.6.1
   Compiling hashbrown v0.11.2
   Compiling memchr v2.5.0
   Compiling anyhow v1.0.57
   Compiling once_cell v1.12.0
   Compiling futures-task v0.3.21
   Compiling futures-util v0.3.21
   Compiling pin-utils v0.1.0
   Compiling fnv v1.0.7
   Compiling itoa v1.0.2
   Compiling futures-sink v0.3.21
   Compiling slab v0.4.6
   Compiling cc v1.0.73
   Compiling httparse v1.7.1
   Compiling ppv-lite86 v0.2.16
   Compiling futures-channel v0.3.21
   Compiling tower-service v0.3.1
   Compiling fastrand v1.7.0
   Compiling remove_dir_all v0.5.3
   Compiling regex-syntax v0.6.26
   Compiling try-lock v0.2.3
   Compiling fixedbitset v0.4.1
   Compiling async-trait v0.1.56
   Compiling httpdate v1.0.2
   Compiling multimap v0.8.3
   Compiling tower-layer v0.3.1
   Compiling heck v0.4.0
   Compiling crc32fast v1.3.2
   Compiling serde v1.0.137
   Compiling bitflags v1.3.2
   Compiling mime v0.3.16
   Compiling adler v1.0.2
   Compiling http-range-header v0.3.0
   Compiling sync_wrapper v0.1.1
   Compiling percent-encoding v2.1.0
   Compiling matchit v0.5.0
   Compiling base64 v0.13.0
   Compiling tracing-core v0.1.26
   Compiling itertools v0.10.3
   Compiling indexmap v1.8.2
   Compiling http v0.2.8
   Compiling cmake v0.1.48
   Compiling miniz_oxide v0.5.3
   Compiling http-body v0.4.5
   Compiling regex v1.5.6
   Compiling want v0.3.0
   Compiling quote v1.0.18
   Compiling flate2 v1.0.24
   Compiling mio v0.8.3
   Compiling socket2 v0.4.4
   Compiling getrandom v0.2.6
   Compiling which v4.2.5
   Compiling tempfile v3.3.0
   Compiling rand_core v0.6.3
   Compiling prost-build v0.10.4
   Compiling rand_chacha v0.3.1
   Compiling petgraph v0.6.2
   Compiling rand v0.8.5
   Compiling prettyplease v0.1.11
   Compiling tokio-macros v1.8.0
   Compiling tracing-attributes v0.1.21
   Compiling prost-derive v0.10.1
   Compiling pin-project-internal v1.0.10
   Compiling async-stream-impl v0.3.3
   Compiling async-stream v0.3.3
   Compiling tokio v1.19.2
   Compiling axum-core v0.2.4
   Compiling pin-project v1.0.10
   Compiling tracing v0.1.34
   Compiling prost v0.10.4
   Compiling tracing-futures v0.2.5
   Compiling prost-types v0.10.1
   Compiling tokio-util v0.7.3
   Compiling tokio-io-timeout v1.2.0
   Compiling tokio-stream v0.1.9
   Compiling tonic-build v0.7.2
   Compiling h2 v0.3.13
   Compiling tower v0.4.12
   Compiling tonic-reflection v0.4.0
   Compiling tower-http v0.3.4
   Compiling hyper v0.14.19
   Compiling axum v0.5.6
   Compiling hyper-timeout v0.4.1
   Compiling tonic v0.7.2
error[E0308]: mismatched types
   --> /Users/pasha/error/target/debug/build/tonic-reflection-a707de0de3873570/out/grpc.reflection.v1alpha.rs:337:33
    |
337 | ...                   accept_compression_encodings,
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `EnabledCompressionEncodings`, found `()`

error[E0308]: mismatched types
   --> /Users/pasha/error/target/debug/build/tonic-reflection-a707de0de3873570/out/grpc.reflection.v1alpha.rs:338:33
    |
338 | ...                   send_compression_encodings,
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `EnabledCompressionEncodings`, found `()`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `tonic-reflection` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by g0hl1n** [comment] 2022-06-07 18:55
Ah, mea culpa... thanks for the clarification!

IMHO this is a duplicate of https://github.com/hyperium/tonic/pull/1004.

Therefore when adding the `compression` feature flag to `tonic-build` in `[build-dependencies]` your example builds correctly:

```
[package]
edition = "2021"
name = "test"
version = "0.0.0"

[[bin]]
name = "test"
path = "test.rs"

[dependencies]
tonic = { version = "0.7.2", features = ["compression"] }
tonic-reflection = "0.4.0"

[build-dependencies]
tonic-build = { version = "0.7.2", features = ["compression"] }
```

**Comment by ppodolsky** [comment] 2022-06-07 19:06
Got it, thank you. I will close the issue because the another one is more appropriate and better described. Thank you!

**Closed** 2022-06-07 19:06 UTC
