### ISSUE TITLE
tonic v0.10.0: h2 protocol error

### ISSUE THREAD

**Issue by Arjentix** [hyperium/tonic#1496] opened 2023-09-02 14:46 UTC
### Version

```bash
$  cargo tree | grep tonic
├── tonic v0.10.0
└── tonic-build v0.10.0
├── tonic v0.10.0 (*)
└── tonic-build v0.10.0 (*)
```

In case you need prost version as well:
```bash
$  cargo tree | grep prost
├── prost v0.12.0
│   └── prost-derive v0.12.0 (proc-macro)
│   ├── prost v0.12.0 (*)
    ├── prost-build v0.12.0
    │   ├── prost v0.12.0
    │   │   └── prost-derive v0.12.0 (proc-macro) (*)
    │   ├── prost-types v0.12.0
    │   │   └── prost v0.12.0 (*)
├── prost v0.12.0 (*)
```

### Platform

`Darwin Amaterasu.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64`

### Description

Just tried new version of tonic & prost in my project which contains of gRPC server and client (with TLS enabled). Everything compiled well, but when running I got this error:

```
Caused by:
   0: status: Unknown, message: "h2 protocol error: http2 error: connection error detected: frame with invalid size", details: [], metadata: MetadataMap { headers: {} }
   1: transport error
   2: http2 error: connection error detected: frame with invalid size
   3: connection error detected: frame with invalid size
```

So I did a rollback to versions where everything works fine:

```bash
$  cargo tree | grep tonic         
├── tonic v0.9.2
└── tonic-build v0.9.2
├── tonic v0.9.2 (*)
└── tonic-build v0.9.2 (*)
```

```bash
$  cargo tree | grep prost
├── prost v0.11.9
│   └── prost-derive v0.11.9 (proc-macro)
│   ├── prost v0.11.9 (*)
    ├── prost-build v0.11.9
    │   ├── prost v0.11.9
    │   │   └── prost-derive v0.11.9 (proc-macro) (*)
    │   ├── prost-types v0.11.9
    │   │   └── prost v0.11.9 (*)
├── prost v0.11.9 (*)
```

**Comment by Arjentix** [comment] 2023-09-02 14:57
Not reproducable when TLS is disabled

**Comment by honsunrise** [comment] 2023-09-06 11:49
Same problem here

**Comment by LucioFranco** [comment] 2023-09-06 13:05
Do you get this error with `0.9` without changing any code? I would need to be able to reproduce this so if you could provide a minimal example that I can triger this with I can investigate.

**Comment by skull8888888** [comment] 2023-09-09 17:22
happened to me too when I added map<string, string> to protobuf

**Comment by Arjentix** [comment] 2023-09-18 12:13
> Do you get this error with 0.9 without changing any code?

Yes

> I would need to be able to reproduce this so if you could provide a minimal example that I can triger this with I can investigate.

I'll try to make one

**Comment by Arjentix** [comment] 2023-09-19 11:39
@LucioFranco , here it is: https://github.com/Arjentix/tonic-bug-repr

It's basically a copy from `examples/tls_client_auth` with some changes

**Comment by LucioFranco** [comment] 2023-09-20 15:06
Ok I don't think this is a tonic bug but more so a change to correct behavior. If you set `http` it will not use TLS so the acceptor handler on a server that accepts TLS fails. Then the return on the tcp stream from the h2 handshake is a tls error which the h2 framer can't parse since there is a frame size issue. So the fix here is to just switch to using `https` if you are speaking to a server that is speaking tls.

I am going to close the issue, feel free to reopen if this isn't solved from what I said above.

**Closed by LucioFranco** 2023-09-20 15:06 UTC

**Comment by andrehp** [comment] 2023-09-28 19:32
@LucioFranco we had the same issue today when upgrading from 0.9 to 0.10. In our case we had set the URLs as `grpc://...` and we had to change to `https://...`

Given that we already initialize the grpc clients with TLS config, we didn't expect this behavior to change.

If this is the expected behavior I think it's worth adding documentation about it.

**Comment by LucioFranco** [comment] 2023-09-28 19:34
@andrehp ah yeah `grpc` I don't think was explicitly supported before anyways. Yeah, it is an intended behavior so we should for sure document this in the `Channel` docs/`Endpoint` docs.

**Comment by AArnott** [comment] 2023-12-14 22:22
I'm hitting this with 0.10.2 even though I'm using https as the scheme. Any ideas?
