### ISSUE TITLE
Self-signed certificates in client

### ISSUE THREAD

**Issue by BratSinot** [hyperium/tonic#1120] opened 2022-10-19 11:36 UTC
### Version
v0.8.2

### Platform
macOS 12.6, but it doesn't matter

### Description

Extent of this: https://github.com/hyperium/tonic/issues/459
Okey, there is no way to use self-signed certificates? How can I get around this?
It has no much sense, because many of gRPC uses inside corporate network and uses self-signed certs.

**Comment by LucioFranco** [comment] 2022-10-19 13:24
I believe this comment is still accurate https://github.com/hyperium/tonic/issues/459#issuecomment-696793643 this is more of a problem with the tls library that is quite strict. Going to close this as its a duplicate of #459

**Closed by LucioFranco** 2022-10-19 13:24 UTC
