### ISSUE TITLE
tonic-build out_file generation does not match what is provided to cargo for building

### ISSUE THREAD

**Issue by sparky8251** [hyperium/tonic#400] opened 2020-07-15 17:36 UTC
### Version

Using version 0.3.0 (for both tonic and tonic-build) 

### Platform

Linux, if you want specifics its Gentoo but that should have no bearing on the report here

### Crates

tonic-build

### Description

If I follow the `helloworld.proto` example but make my `build.rs` contain the following:

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(false)
        .build_client(false)
        .out_dir("src/protos")
        .compile(
            &["/protos/helloworld.proto"],
            &["/protos/"],
        )?;
    Ok(())
}
```

The generated `src/protos/helloworld.rs` will only contain:

```rust
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloRequest {
    /// Request message contains the name to be greeted
    #[prost(string, tag = "1")]
    pub name: std::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloReply {
    /// Reply contains the greeting message
    #[prost(string, tag = "1")]
    pub message: std::string::String,
}
```

This means that the server code which contains the line `impl Greeter for MyGreeter { ... }` should not compile if the build options impact more than just the `out_file`. But for me, it compiles just fine which is confusing at best, and a bug at worst.

The only potential hiccup with this in case it can't be replicated is that I have a workspace where the client and server both exist in separate crates. I know that workspaces kinda sorta share build artifacts, so maybe that's how this is working for me?

**Comment by LucioFranco** [comment] 2020-07-27 18:57
> should not compile if the build options impact more than just the out_file

Could you clarify what you mean by this? I am not fully tracking what the problem is here.

**Comment by sparky8251** [comment] 2020-07-28 11:11
Well, if the `build.rs` options can be used to change what is sent to the out_file, why does it fail to change what is sent to the build process?

In the above example, the `Greeter` service is not present in the out_file, but its used in `main()` and the build properly completes somehow.

**Comment by LucioFranco** [comment] 2020-07-29 14:18
It may still be cached? I am not sure why it would show up, but I would ensure you are building from a clean workspace.

**Comment by sparky8251** [comment] 2020-08-26 17:44
Right, and I did. Which is why I ended up opening this.

**Comment by LucioFranco** [comment] 2020-08-26 19:56
@sparky8251 would you be able to create a small reproduction of this?

**Comment by alce** [comment] 2020-09-02 14:07
@sparky8251 One possibility is that you are generating one file but including a stale one in your code. Try following the path to the generated module from the file where you are using it. From what I can see, it should be something like `use protos`, not  the `tonic::include_proto` macro. If your server code compiles, you must be bringing the types into scope somehow from somewhere.

Without knowing more about your setup it is hard to figure out what is causing confusion.  You say you have a workspace with a client and server crates but the code you showed only generates code for one.

Do you have your proto files in a third crate and generate from there? If so, you'll need to call `tonic_build::compile` twice or do you use this third crate as a dependency? Or do you have a copy of your `.proto` files on each crate and a `build.rs` on each? Are all the crates involved declared as members of the workspace in Cargo.toml?

I have used a similar setup and a few different ones without problems once I had my imports correctly.

**Comment by alce** [comment] 2020-09-24 00:01
Closing this, assuming it was resolved. Please add a comment and we will re-open if you have further questions.

**Closed by alce** 2020-09-24 00:01 UTC
Labels: bug, crate/tonic

**Comment by noelzubin** [comment] 2021-03-03 05:55
How was this resolved ?. Does it makes sense to import the generated code into a separate packaage so that it can be imported from multiple places. Say like (client/server)

**Comment by LucioFranco** [comment] 2021-03-12 21:29
Its possible to generate the code into its own pacakge.
