### ISSUE TITLE
Bump hyper / http / http-body to 1.x version

### ISSUE THREAD

**Issue by tisonkun** [hyperium/tonic#1668] opened 2024-03-29 04:58 UTC
hyper released 1.0 this year. So do http and http-body.

This is a request as a reminder here to upgrade these libraries to 1.x baseline so that tonic can work together with newer hyper / reqwest, axum version without glue conversions.

I tried to bump it but the new struct and type signature is broken a lot that a newcomer can hardly catch it up.

Perhaps you are already working on this; don't treat this issue an urgent, but as a todo ticket.

**Comment by djc** [comment] 2024-03-29 16:20
Please check for open issues before you file new ones. This is just a duplicate of #1579.

**Comment by tisonkun** [comment] 2024-03-29 16:29
Thank you! Closed as duplicate.

**Closed** 2024-03-29 16:29 UTC
