### ISSUE TITLE
Question about proxyless grpc

### ISSUE THREAD

**Issue by GOVYANSONG** [hyperium/tonic#1109] opened 2022-10-11 17:49 UTC
while we expand our effort to optimize deployment efficiency, proxyless grpc looks very promising. Not sure how to frame the question or if even relevent to tonic project, does tonic support proxyless grpc or it can be achieved with existing features.

**Comment by LucioFranco** [comment] 2022-10-12 14:06
I've never heard of the term proxyless grpc can you explain more what that is?

**Comment by GOVYANSONG** [comment] 2022-10-12 16:05
https://istio.io/latest/blog/2021/proxyless-grpc/
https://cloud.google.com/traffic-director/docs/proxyless-overview

**Comment by atollena** [comment] 2022-10-15 07:10
This can probably be marked as duplicate of https://github.com/hyperium/tonic/issues/479. Proxyless is Google products terminology for gRPC configured directly via their xDS control plane directly (istio or traffic director).

**Closed** 2022-10-17 13:55 UTC
