### ISSUE TITLE
Build warnings in proto defs 

### ISSUE THREAD

**Issue by hntd187** [hyperium/tonic#295] opened 2020-03-14 15:37 UTC
### Version
0.1.1

### Platform
All (happens on windows, osx and linux)

### Description

I get build warnings like the following
```
warning: type `raft_requestSvc` should have an upper camel case name
   --> C:\Users\shcar\IdeaProjects\Toshi\target\debug\build\toshi-proto-979910a1e8f4b4da\out/clusterrpc.rs:574:28
    |
574 |                     struct raft_requestSvc<T: IndexService>(pub Arc<T>);
    |                            ^^^^^^^^^^^^^^^ help: convert the identifier to upper camel case: `RaftRequestSvc`

warning: type `joinSvc` should have an upper camel case name
   --> C:\Users\shcar\IdeaProjects\Toshi\target\debug\build\toshi-proto-979910a1e8f4b4da\out/clusterrpc.rs:601:28
    |
601 |                     struct joinSvc<T: IndexService>(pub Arc<T>);
    |                            ^^^^^^^ help: convert the identifier to upper camel case: `JoinSvc`
```

My proto def can be found here.
https://github.com/toshi-search/Toshi/blob/master/toshi-proto/proto/cluster.proto

**Comment by jen20** [comment] 2020-03-19 16:52
Hi @hntd187! Thanks for opening a bug report. This reproduces easily using the latest release of `tonic` and `tonic-build`. The issue is caused by `service_ident` in the various generated files being derived from the gRPC method identifier, for example:

https://github.com/hyperium/tonic/blob/f65cda1ea0a190fe07c4f8d91473baad9a6f1f77/tonic-build/src/server.rs#L257

There seem to be two approaches to resolving this:

 - Transform the method identifier from the conventional gRPC lower snake case into the upper camel case expected by Rust type names when generating `service_ident`. My hunch is that this is OK, but I'm not 100% certain this could never lead to duplicate type names in a protocol buffers package with names constructed in some manner.

- Annotate the type names to allow non-conventional type names (using `#[allow(non_camel_case_types)]`) - since the structures in question are never exposed in public APIs anyway, this seems less invasive and could be build directly into the templates.

@LucioFranco Any thoughts on which approach you'd prefer here?

**Comment by LucioFranco** [comment] 2020-03-19 17:00
@jen20 the `allow` solution should be fine :+1: its quick and easy.

**Comment by LucioFranco** [comment] 2020-03-19 17:00
Also to note, this change will go out with 0.2 which is slightly on hold for the moment, so when this gets fixed on master I'd suggest users to work off of master for a bit.

**Closed** 2020-03-19 19:18 UTC
Labels: bug, crate/build

**Comment by bmulder-innoseis** [comment] 2022-05-31 08:58
this also happens in streaming calls.
proto:
```
service Foo {
rpc bar (barRequest) returns (stream barResponse);
}
```
generated server code:
```
pub mod foo_server {
#![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    ///Generated trait containing gRPC methods that should be implemented for use with FooServer.
    #[async_trait]
    pub trait Foo: Send + Sync + 'static {
        ///Server streaming response type for the eventStream method.
        type barStream: futures_core::Stream<
                Item = Result<super::Events, tonic::Status>,
            >
            + Send
            + 'static;
         [...]
    }
}
```
when compiling:
```
    |
135 |         type barStream: futures_core::Stream<
    |              ^^^^^^^^^^^^^^^^^ help: convert the identifier to upper camel case: `BarStream`
    |
    = note: `#[warn(non_camel_case_types)]` on by default
```

**Comment by cvik** [comment] 2025-03-11 13:39
The last problem is still very much a problem, I would say.
